import data from "./games.json";
import type { Game } from "../../../scripts/sync-games";

export type { Game };

/** Generated by `bun run scripts/sync-games.ts` — edit the Obsidian notes, not the JSON. */
export const games = data as Game[];
